apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  labels:
    purpose: vllm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: managed-csi-premium-vllm
  resources:
    requests:
      storage: 50Gi