apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama70binstruct-pvc
  namespace: llama70binstruct
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
  volumeMode: Filesystem