apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llama-33-70b-instruct-hf
    kubernetes.azure.com/scalesetpriority: spot
    purpose: llama-demo
    run: llama-33-70b-instruct-hf
  name: llama-33-70b-instruct-hf
  namespace: llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-33-70b-instruct-hf
      kubernetes.azure.com/scalesetpriority: spot
      purpose: llama-demo
      run: llama-33-70b-instruct-hf
  template:
    metadata:
      labels:
        app: llama-33-70b-instruct-hf
        kubernetes.azure.com/scalesetpriority: spot
        purpose: llama-demo
        run: llama-33-70b-instruct-hf
    spec:
      containers:
      - command:
        - text-generation-launcher
        - --model-id
        - meta-llama/Llama-3.3-70B-Instruct
        - --quantize
        - bitsandbytes
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hf-token-secret
        image: ghcr.io/huggingface/text-generation-inference:3.1.0
        name: text-generation-inference
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            nvidia.com/gpu: 2
          requests:
            nvidia.com/gpu: 2
        volumeMounts:
        - mountPath: /data
          name: llama370b
        - mountPath: /dev/shm
          name: shm
      nodeSelector:
        purpose: llama-demo
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      - effect: NoSchedule
        key: sku
        operator: Equal
        value: gpu
      volumes:
      - name: llama370b
        persistentVolumeClaim:
          claimName: pvc-llama370b-instruct-hf
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: shm