apiVersion: v1
kind: Service
metadata:
  name: llama70binstruct-svc
  namespace: llama70binstruct
spec:
  ports:
  - name: http-llama70binstruct
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: llama70binstruct
  sessionAffinity: None
  type: ClusterIP