apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kubernetes.azure.com/scalesetpriority: spot
    purpose: llama-demo
  name: pvc-llama370b-instruct-hf
  namespace: llama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: managed-csi-premium