apiVersion: ray.io/v1
kind: RayService
metadata:
  name: gptoss-120b-a100
spec:
  serveConfigV2: |
    applications:
    - name: llms
      import_path: ray.serve.llm:build_openai_app
      route_prefix: "/"
      args:
        llm_configs:
        - model_loading_config:
            model_id: gpt-oss-120b
            model_source: openai/gpt-oss-120b
          engine_kwargs:
            dtype: bfloat16
            max_model_len: 1024
            device: auto
            gpu_memory_utilization: 0.75
          deployment_config:
            autoscaling_config:
              min_replicas: 1
              max_replicas: 4
              target_ongoing_requests: 64
            max_ongoing_requests: 128
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          nodeSelector:
            purpose: ray-head
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.33.0.914af0-py311
            resources:
              limits:
                cpu: "8"
                memory: "16Gi"
              requests:
                cpu: "8"
                memory: "16Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hf-token-secret                  
          tolerations:
            - effect: NoSchedule
              key: sku
              operator: Equal
              value: ray
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          nodeSelector:
            purpose: llm-rayserve
          containers:
          - name: llm
            image: rayproject/ray-ml:2.33.0.914af0-py311
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hf-token-secret
            resources:
              limits:
                nvidia.com/gpu: "4"
          # Please add the following taints to the GPU node.
          tolerations:
            - effect: NoSchedule
              key: sku
              operator: Equal
              value: gpu