apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llama-33-70b-instruct-hf
    # kubernetes.azure.com/scalesetpriority: spot
    purpose: llama-demo
    run: llama-33-70b-instruct-hf 
  name: llama-33-70b-instruct-hf
  namespace: llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-33-70b-instruct-hf
      # kubernetes.azure.com/scalesetpriority: spot
      purpose: llama-demo
      run: llama-33-70b-instruct-hf
  template:
    metadata:
      labels:
        app: llama-33-70b-instruct-hf
        # kubernetes.azure.com/scalesetpriority: spot
        purpose: llama-demo
        run: llama-33-70b-instruct-hf
    spec:
      containers:
      - command: ["/bin/sh", "-c"]
        args: [
          "vllm serve meta-llama/Llama-3.2-3B-Instruct --trust-remote-code --dtype float16 --max-model-len 4096"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hf-token-secret
        image: vllm/vllm-openai:latest
        name: tllama-33-70b-instruct-hf
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            nvidia.com/gpu: 4
        volumeMounts:
        - mountPath: /data
          name: llama370b
        - mountPath: /dev/shm
          name: shm
      nodeSelector:
        purpose: llama-demo
      tolerations:
      - effect: NoSchedule
        # key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
      - effect: NoSchedule
        key: sku
        operator: Equal
        value: gpu
      volumes:
      - name: llama370b
        persistentVolumeClaim:
          claimName: pvc-llama370b-instruct-hf
      - emptyDir:
          medium: Memory
          sizeLimit: 10Gi
        name: shm